### ISSUE TITLE
VectorUtil.RotateBy(ref) does the wrong calculation

### ISSUE THREAD

**Issue by Bunny83** [lordofduct/spacepuppy-unity-framework-3.0#4]
As it was pointed out in [this forum post](https://forum.unity.com/threads/whats-the-best-way-to-rotate-a-vector2-in-unity.729605/#post-6187407) you should [swap the two assignments](https://github.com/lordofduct/spacepuppy-unity-framework-3.0/blob/8194de9aa07d249f9d90d3c2003cee03f39f0f6e/SpacepuppyUnityFramework/Utils/VectorUtil.cs#L237-L238) of v.x and v.y. Otherwise the calculation of v.y is wrong as it would use the already modified x value.

You specifically stored the new x value in `rx`, but the assignment `v.x = (float)rx;` has to be done last or it's pretty pointless to use rx at all.
An alternative could be to also use the Vector2 constructor and create a new vector2 value out of the two new component values and assign the whole vector:

`v = new Vector2(float)(v.x * ca - v.y * sa, (float)(v.x * sa + v.y * ca));`

**Comment by lordofduct** [comment]
fixed
